# Generated by Django 5.0.3 on 2024-11-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenamedCaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
    ]
